INSERT INTO BodyTypes(BodyTypeName) VALUES('Cabrio')
INSERT INTO BodyTypes(BodyTypeName) VALUES('Coupe')
INSERT INTO BodyTypes(BodyTypeName) VALUES('Sedan')
INSERT INTO BodyTypes(BodyTypeName) VALUES('Hatchback 3 kapı')
INSERT INTO BodyTypes(BodyTypeName) VALUES('Hatchback 5 kapı')

INSERT INTO Fuels(FuelName) VALUES('Benzin')
INSERT INTO Fuels(FuelName) VALUES('Benzin & LPG')
INSERT INTO Fuels(FuelName) VALUES('Dizel')
INSERT INTO Fuels(FuelName) VALUES('Hybrid')
INSERT INTO Fuels(FuelName) VALUES('Elektrik')

INSERT INTO OperationClaims(OperationClaimName) VALUES('admin')
INSERT INTO OperationClaims(OperationClaimName) VALUES('company')
INSERT INTO OperationClaims(OperationClaimName) VALUES('customer')

INSERT INTO Tractions(TractionName) VALUES('Önden Çekiş')
INSERT INTO Tractions(TractionName) VALUES('Arkadan İtiş')
INSERT INTO Tractions(TractionName) VALUES('4WD (Sürekli)')
INSERT INTO Tractions(TractionName) VALUES('AWD (Elektronik)')

INSERT INTO Transmissions(TransmissionName) VALUES('Manuel')
INSERT INTO Transmissions(TransmissionName) VALUES('Otomatik')

INSERT INTO Brands(BrandName) VALUES('Audi')
INSERT INTO Brands(BrandName) VALUES('BMW')
INSERT INTO Brands(BrandName) VALUES('Dacia')
INSERT INTO Brands(BrandName) VALUES('Fiat')
INSERT INTO Brands(BrandName) VALUES('Ford')
INSERT INTO Brands(BrandName) VALUES('Honda')
INSERT INTO Brands(BrandName) VALUES('Hyundai')
INSERT INTO Brands(BrandName) VALUES('Toyota')
INSERT INTO Brands(BrandName) VALUES('Volkswagen')
INSERT INTO Brands(BrandName) VALUES('Volvo')

INSERT INTO Models(BrandId, ModelName) VALUES(1, 'A3')
INSERT INTO Models(BrandId, ModelName) VALUES(1, 'A4')
INSERT INTO Models(BrandId, ModelName) VALUES(1, 'A5')
INSERT INTO Models(BrandId, ModelName) VALUES(1, 'A6')
INSERT INTO Models(BrandId, ModelName) VALUES(1, 'A7')

INSERT INTO Models(BrandId, ModelName) VALUES(2, '320')
INSERT INTO Models(BrandId, ModelName) VALUES(2, '325')
INSERT INTO Models(BrandId, ModelName) VALUES(2, '425')
INSERT INTO Models(BrandId, ModelName) VALUES(2, '430')

INSERT INTO Models(BrandId, ModelName) VALUES(3, 'Sandero')
INSERT INTO Models(BrandId, ModelName) VALUES(3, 'Duster')

INSERT INTO Models(BrandId, ModelName) VALUES(4, 'Linea')
INSERT INTO Models(BrandId, ModelName) VALUES(4, 'Egea')
INSERT INTO Models(BrandId, ModelName) VALUES(4, 'Punto')

INSERT INTO Models(BrandId, ModelName) VALUES(5, 'Focus')
INSERT INTO Models(BrandId, ModelName) VALUES(5, 'Mondeo')
INSERT INTO Models(BrandId, ModelName) VALUES(5, 'Fiesta')
INSERT INTO Models(BrandId, ModelName) VALUES(5, 'Fusion')
INSERT INTO Models(BrandId, ModelName) VALUES(5, 'Mustang')

INSERT INTO Models(BrandId, ModelName) VALUES(6, 'Civic')
INSERT INTO Models(BrandId, ModelName) VALUES(6, 'Accord')
INSERT INTO Models(BrandId, ModelName) VALUES(6, 'City')
INSERT INTO Models(BrandId, ModelName) VALUES(6, 'S2000')

INSERT INTO Models(BrandId, ModelName) VALUES(7, 'Accent')
INSERT INTO Models(BrandId, ModelName) VALUES(7, 'Elentra')
INSERT INTO Models(BrandId, ModelName) VALUES(7, 'Getz')
INSERT INTO Models(BrandId, ModelName) VALUES(7, 'i20')
INSERT INTO Models(BrandId, ModelName) VALUES(7, 'i30')

INSERT INTO Models(BrandId, ModelName) VALUES(8, 'Auris')
INSERT INTO Models(BrandId, ModelName) VALUES(8, 'Corolla')
INSERT INTO Models(BrandId, ModelName) VALUES(8, 'Supra')

INSERT INTO Models(BrandId, ModelName) VALUES(9, 'Jetta')
INSERT INTO Models(BrandId, ModelName) VALUES(9, 'Passat')
INSERT INTO Models(BrandId, ModelName) VALUES(9, 'Golf')
INSERT INTO Models(BrandId, ModelName) VALUES(9, 'Polo')
INSERT INTO Models(BrandId, ModelName) VALUES(9, 'Bora')

INSERT INTO Models(BrandId, ModelName) VALUES(10, 'S40')
INSERT INTO Models(BrandId, ModelName) VALUES(10, 'S60')
INSERT INTO Models(BrandId, ModelName) VALUES(10, 'S70')
INSERT INTO Models(BrandId, ModelName) VALUES(10, 'S80')
INSERT INTO Models(BrandId, ModelName) VALUES(10, 'S90')
